name: CI Angular App

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Inicio de Trabajo
        run: |
          echo "Iniciando el trabajo de CI para la aplicación Angular"
          echo "Verificando el entorno de ejecución"

      - name: Checkout Repositorio
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Variable de GITHUB_ACTOR que contiene el nombre del usuario que ha iniciado la acción
      - name: Obtener usuario que acciona el push
        run: |
          echo "Usuario que acciona el workflow: ${{ github.actor }}"
          echo "Evento: ${{ github.event_name }}"

      - name: Instalar dependencias
        run: npm ci

      - name: Finalizar Trabajo
        run: echo "Trabajo de CI completado exitosamente"